export const Actions = {
    //SAVE
    COUNTRY_CREATION_SAVE: 'COUNTRY_CREATION_SAVE',
        COUNTRY_CREATION_SAVE_SUCCESS: 'COUNTRY_CREATION_SAVE_SUCCESS',
        COUNTRY_CREATION_SAVE_ERROR: 'COUNTRY_CREATION_SAVE_ERROR',
    //GET
    GET_COUNTRIES: 'GET_COUNTRIES',
    //SELECT
    SELECT_COUNTRY: 'COUNTRY_SELECTED'
};

