export const Actions = {
    COUNTRY_CREATION_SAVE: 'COUNTRY_CREATION_SAVE',
        COUNTRY_CREATION_SAVE_SUCCESS: 'COUNTRY_CREATION_SAVE_SUCCESS',
        COUNTRY_CREATION_SAVE_ERROR: 'COUNTRY_CREATION_SAVE_ERROR',
    GET_COUNTRIES: 'GET_COUNTRIES',
    SELECT_COUNTRY: 'COUNTRY_SELECTED',
    UPDATE_COUNTRY: 'UPDATE_COUNTRY'
};

